---
- name: Provision Rocky Linux
  hosts: all
  become: yes
  tasks:
    - name: Install basic packages
      yum:
        name:
          - git
          - wget
          - vim
        state: present

    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
